#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD="$(tput bold)"; DIM="$(tput dim)"; RESET="$(tput sgr0)"
  GREEN="$(tput setaf 2)"; YELLOW="$(tput setaf 3)"; BLUE="$(tput setaf 4)"
else
  BOLD=""; DIM=""; RESET=""; GREEN=""; YELLOW=""; BLUE=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  if [[ -t 1 ]]; then clear; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '%s%s%s\n\n' "$BOLD" "$1" "$RESET"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  _clear
  printf '%s[%d/%d] %s%s\n\n' "$BOLD" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  say "Opening: $url"
  if command -v wslview >/dev/null 2>&1; then wslview "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v open >/dev/null 2>&1; then open "$url" >/dev/null 2>&1 || true
  else note "(couldn't auto-open — copy the URL above)"; fi
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue...}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply
  printf '  %s [y/N] ' "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy]$ ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  local key="$1"
  [[ -f "$ENV_FILE" ]] || return 0
  grep -m1 "^${key}=" "$ENV_FILE" 2>/dev/null | cut -d= -f2- || true
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" default value
  default="$(_existing "$key")"
  if [[ -n "$default" ]]; then
    printf '  %s [%s]: ' "$prompt" "$default"
  else
    printf '  %s: ' "$prompt"
  fi
  read -r value || true
  [[ -z "$value" && -n "$default" ]] && value="$default"
  printf -v "$key" '%s' "$value"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" value
  printf '  %s (hidden): ' "$prompt"
  read -rs value || true
  printf '\n'
  printf -v "$key" '%s' "$value"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2"
  touch "$ENV_FILE"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    local tmp; tmp="$(mktemp)"
    sed "s|^${key}=.*|${key}=${value}|" "$ENV_FILE" > "$tmp" && mv "$tmp" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
  WRITTEN_ENV+=("$key")
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh CLI not found — set secret '$name' manually in GitHub → Settings → Secrets"
    SKIPPED+=("secret:$name")
    return 0
  fi
  if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
  else
    warn "Could not set secret '$name' via gh — set it manually"
    SKIPPED+=("secret:$name")
  fi
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh CLI not found — set variable '$name' manually in GitHub → Settings → Variables"
    SKIPPED+=("var:$name")
    return 0
  fi
  if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
    :
  else
    warn "Could not set variable '$name' via gh — set it manually"
    SKIPPED+=("var:$name")
  fi
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '%sDone.%s\n\n' "$GREEN$BOLD" "$RESET"
  if [[ ${#WRITTEN_ENV[@]} -gt 0 ]]; then
    printf 'Written to %s: %s\n' "$ENV_FILE" "${WRITTEN_ENV[*]}"
  fi
  if [[ ${#WRITTEN_SECRET[@]} -gt 0 ]]; then
    printf 'GitHub secrets/vars set: %s\n' "${WRITTEN_SECRET[*]}"
  fi
  if [[ ${#SKIPPED[@]} -gt 0 ]]; then
    printf '%sManual follow-ups still needed: %s%s\n' "$YELLOW" "${SKIPPED[*]}" "$RESET"
  fi
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Będzie Igła — VPS-1 launch (2.0.0)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

banner "Będzie Igła — VPS-1 launch wizard"
say "Walks through buying OVH VPS-1, pointing DNS, provisioning the box,"
say "wiring GitHub Actions deploy secrets, TLS, SMTP mailbox and DKIM, then"
say "the first CI deploy and a live smoke test. Re-run anytime — answers"
say "with an existing .env value show as the default."
pause

# ── Stage 1: order the VPS ─────────────────────────────────────────────────
stage "Order OVH VPS-1"
say "Buy the smallest OVH VPS (VPS-1, Ubuntu LTS image) if not done yet."
open_url "https://www.ovhcloud.com/en/vps/"
step "Choose VPS-1, Ubuntu 22.04/24.04 LTS, your region, complete checkout."
step "Once provisioned, OVH emails/shows the server's public IPv4 address."
ask VPS_HOST "Paste the VPS public IP (or hostname):"
write_env VPS_HOST "$VPS_HOST"
note "This IP is also the GitHub secret VPS_HOST — set further down."

# ── Stage 2: DNS ────────────────────────────────────────────────────────────
stage "Point bedzieigla.pl DNS at the VPS"
say "In your DNS provider (OVH domain panel or wherever bedzieigla.pl is"
say "managed), create/update A records for the apex and www:"
open_url "https://www.ovh.com/manager/#/web/domain/bedzieigla.pl/zone"
step "A record: bedzieigla.pl      → $VPS_HOST"
step "A record: www.bedzieigla.pl  → $VPS_HOST"
note "DNS propagation can take minutes to hours — certbot (stage 5) needs it live."
pause "Press Enter once both A records are saved..."

# ── Stage 3: run setup-vps.sh ───────────────────────────────────────────────
stage "Provision the VPS (deploy/setup-vps.sh)"
say "This installs ufw, the 'deploy' user, Node 22, pnpm, PM2, Nginx,"
say "certbot, fail2ban and the security-headers snippet."
step "Copy the script to the VPS:"
note "  scp deploy/setup-vps.sh root@${VPS_HOST}:/root/setup-vps.sh"
step "Run it as root over SSH:"
note "  ssh root@${VPS_HOST} 'bash /root/setup-vps.sh'"
warn "VPS_USER must end up being exactly 'deploy' — ecosystem.config.cjs (cwd) and"
warn "nginx.conf.template (root path) both hardcode /home/deploy/bedzieigla."
pause "Press Enter once the script has finished on the VPS..."

# ── Stage 4: CI deploy SSH keypair + GitHub secrets ─────────────────────────
stage "CI deploy SSH key + GitHub Actions secrets"
say "GitHub Actions needs its own keypair to SSH into the 'deploy' user."
if confirm "Generate a fresh ed25519 deploy keypair now in ./.deploy_key{,.pub}?"; then
  ssh-keygen -t ed25519 -N "" -f ./.deploy_key -C "github-actions-deploy@bedzieigla" >/dev/null
  say "Generated ./.deploy_key (private) and ./.deploy_key.pub (public)."
else
  note "Skipping generation — point at an existing keypair below."
fi
step "Append the PUBLIC key to the VPS deploy user's authorized_keys:"
note "  cat .deploy_key.pub | ssh root@${VPS_HOST} 'cat >> /home/deploy/.ssh/authorized_keys'"
pause "Press Enter once the public key is installed on the VPS..."
VPS_USER="deploy"
write_env VPS_USER "$VPS_USER"
if [[ -f ./.deploy_key ]]; then
  set_secret VPS_SSH_KEY "$(cat ./.deploy_key)"
else
  warn "No local ./.deploy_key found — set the VPS_SSH_KEY secret manually with the private key contents."
  SKIPPED+=("secret:VPS_SSH_KEY")
fi
set_secret VPS_HOST "$VPS_HOST"
set_secret VPS_USER "$VPS_USER"
note "Old FTP_* secrets (if any remain from the pre-2.0.0 static host) are now unused and can be deleted."

# ── Stage 5: Nginx bootstrap + TLS ──────────────────────────────────────────
stage "Nginx HTTP bootstrap + certbot TLS"
say "TLS block in deploy/nginx.conf.template needs certs to exist before nginx"
say "will load it — bootstrap HTTP-only first (see the note atop that file)."
step "On the VPS as root: create /etc/nginx/sites-available/bedzieigla.pl with"
step "  ONLY the port-80 server block from deploy/nginx.conf.template, but with"
step "  'root /home/deploy/bedzieigla/build/client;' instead of the redirect."
step "Symlink it into sites-enabled, then: nginx -t && systemctl reload nginx"
step "Issue the certificate:"
note "  ssh root@${VPS_HOST} 'certbot --nginx -d bedzieigla.pl -d www.bedzieigla.pl'"
step "Now install deploy/nginx.conf.template IN FULL (certbot's ssl_certificate"
step "  lines are preserved), then: nginx -t && systemctl reload nginx"
pause "Press Enter once https://bedzieigla.pl loads (even with a placeholder app)..."

# ── Stage 6: OVH mailbox password + VPS .env ────────────────────────────────
stage "OVH mailbox password + server-side .env"
say "kontakt@bedzieigla.pl must be a real OVH MX Plan mailbox (not an alias) —"
say "SMTP_USER doubles as the From address, required for SPF to pass."
open_url "https://www.ovh.com/manager/#/web/exchange"
step "Set/reset the password of the kontakt@bedzieigla.pl mailbox."
ask_secret SMTP_PASS "Paste the mailbox password:"
ask CONTACT_TO_EMAIL "Gosia's inbox that should receive submissions (her Gmail):"
write_env SMTP_PASS "$SMTP_PASS"
write_env CONTACT_TO_EMAIL "$CONTACT_TO_EMAIL"
say "On the VPS, create /home/deploy/bedzieigla/.env from deploy/.env.example"
say "with these real values, then: chmod 600 /home/deploy/bedzieigla/.env"
note "  SMTP_HOST=ssl0.ovh.net"
note "  SMTP_PORT=465"
note "  SMTP_USER=kontakt@bedzieigla.pl"
note "  SMTP_PASS=<value just entered>"
note "  CONTACT_TO_EMAIL=<value just entered>"
pause "Press Enter once /home/deploy/bedzieigla/.env exists on the VPS (chmod 600)..."
note "Also copy deploy/ecosystem.config.cjs to /home/deploy/bedzieigla/ on the VPS if not already there."

# ── Stage 7: DKIM ────────────────────────────────────────────────────────────
stage "Enable DKIM signing (before any DMARC record)"
say "OVH MX Plan panel flags DKIM red under Diagnostic until enabled — do this"
say "BEFORE adding a DMARC record, so DMARC reports can tell a forwarding hop"
say "from a real auth failure."
open_url "https://www.ovh.com/manager/#/web/exchange"
step "Find bedzieigla.pl → Diagnostic/DKIM → enable signing (publishes the"
step "  selector's DNS TXT record automatically in most OVH setups)."
if confirm "Is DKIM now showing green/enabled in the OVH panel?"; then
  say "Good — safe to add a DMARC record later if desired."
else
  warn "Leave DMARC alone until DKIM is confirmed green."
fi
pause

# ── Stage 8: build-time GitHub secrets/vars (VITE_*, SITE_URL) ─────────────
stage "Build-time GitHub Actions secrets/variables"
say "These are baked into the client bundle at CI build time (never on the VPS)."
open_url "https://analytics.google.com/"
step "Admin → Data Streams → Web → copy the Measurement ID (G-XXXXXXXXXX),"
step "  or leave blank to keep analytics disabled."
ask VITE_GA4_ID "GA4 Measurement ID (blank to skip):"
ask VITE_S3_LIST_URL "OVH S3 ListObjectsV2 URL (blank = picsum test photos):"
ask VITE_S3_PUBLIC_URL "OVH S3 public base URL, no trailing slash:"
ask VITE_S3_PREFIX "S3 gallery folder prefix [gallery/]:"
[[ -z "$VITE_S3_PREFIX" ]] && VITE_S3_PREFIX="gallery/"
for k in VITE_GA4_ID VITE_S3_LIST_URL VITE_S3_PUBLIC_URL VITE_S3_PREFIX; do
  write_env "$k" "${!k}"
  set_secret "$k" "${!k}"
done
ask SITE_URL "Production site URL for the GH Actions 'production' environment [https://bedzieigla.pl]:"
[[ -z "$SITE_URL" ]] && SITE_URL="https://bedzieigla.pl"
write_env SITE_URL "$SITE_URL"
set_var SITE_URL "$SITE_URL"
note "SITE_URL is read as \${{ vars.SITE_URL }} by the 'production' environment in deploy.yml."

# ── Stage 9: first deploy + smoke test ──────────────────────────────────────
stage "First CI deploy + live smoke test"
say "Everything above is now in place. Trigger the deploy:"
step "git push origin release-2.0.0:main   (or merge the release branch to main)"
open_url "https://github.com"
step "Watch the 'Deploy → OVH Perso' workflow run green end-to-end."
note "First run: on the VPS you likely need 'pm2 start ecosystem.config.cjs && pm2 save'"
note "once manually (see deploy/setup-vps.sh's step-6 output) — after that, CI's"
note "'pm2 reload' keeps it updated on every push."
step "Then open https://bedzieigla.pl, submit the contact form with a real photo,"
step "  and confirm it arrives at CONTACT_TO_EMAIL at full quality."
note "Also update <lastmod> in static/sitemap.xml to today's date and commit it."
pause "Press Enter once the live smoke test has passed..."

finish
